version: '3'

services:

  nginx:
    image: nginx
    depends_on:
      - admin
      - api
    volumes:
      - admin:/srv/admin:ro
      - ./etc/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    ports:
      - "8080:8080"
    command: [nginx-debug, '-g', 'daemon off;']

  admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    volumes:
      - admin:/srv/admin/dist
    environment:
      BASENAME: /admin
      API_ENDPOINT: /api/v1
      STATIC_ENDPOINT: /static

  api:
    depends_on:
      - db
    build: ./node-server
    restart: always
    volumes:
      - static:/static
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: aws-photo
      DB_PASSWORD: aws-photo
      STATIC_DIR: /static
    entrypoint:  sh -c '/srv/scripts/wait-for db:3306 -- pm2-docker dist/app.js'

  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: aws-photo
      MYSQL_DATABASE: aws-photo
      MYSQL_USER: aws-photo
      MYSQL_PASSWORD: aws-photo

volumes:
    db_data:
    static:
    admin:
